name: Deployment To Staging

on:
    push:
        branches: 
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: install dep
              run: npm i

            - name: run test ${{ secrets.DOCKERHUB_TOKEN }}
              run: npm run test

    build-and-push:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: build docker image
              run: docker build -t talel12/backend-session16 .

            - name: tag image by version
              run: docker tag talel12/backend-session16 talel12/backend-session16:v1

            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: push image to dockerhub
              run: docker push talel12/backend-session16:v1

            - name: push image to dockerhub
              run: docker push talel12/backend-session16

    Deploy:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
          - uses: appleboy/ssh-action@v1
            with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                script: |
                    cd /home/user/devops-script/backend
                    docker compose pull backend-api
                    docker compose up -d backend-api --force-recreate